# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1061, 762)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:white;")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1061, 831))
        self.stackedWidget.setObjectName("stackedWidget")
        self.widget_1 = QtWidgets.QWidget()
        self.widget_1.setObjectName("widget_1")
        self.label = QtWidgets.QLabel(self.widget_1)
        self.label.setGeometry(QtCore.QRect(320, 100, 681, 51))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_1)
        self.label_2.setGeometry(QtCore.QRect(230, 140, 761, 51))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;\n"
"color: grey;")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.widget_1)
        self.label_5.setGeometry(QtCore.QRect(25, 135, 21, 20))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("icons/ellipsis.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_1)
        self.label_6.setGeometry(QtCore.QRect(170, 240, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_1)
        self.label_7.setGeometry(QtCore.QRect(410, 240, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_1)
        self.label_8.setGeometry(QtCore.QRect(520, 360, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_1)
        self.label_9.setGeometry(QtCore.QRect(120, 360, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_1)
        self.label_10.setGeometry(QtCore.QRect(170, 480, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget_1)
        self.label_11.setGeometry(QtCore.QRect(500, 480, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget_1)
        self.label_12.setGeometry(QtCore.QRect(800, 480, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit.setGeometry(QtCore.QRect(130, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_2.setGeometry(QtCore.QRect(450, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 400, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_4.setGeometry(QtCore.QRect(450, 400, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 520, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_6.setGeometry(QtCore.QRect(450, 520, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_7.setGeometry(QtCore.QRect(780, 520, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_19 = QtWidgets.QLabel(self.widget_1)
        self.label_19.setGeometry(QtCore.QRect(240, 40, 581, 55))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("icons/Step1.PNG"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.stackedWidget.addWidget(self.widget_1)
        self.widget_2 = QtWidgets.QWidget()
        self.widget_2.setObjectName("widget_2")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(260, 100, 741, 51))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: none;\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setGeometry(QtCore.QRect(180, 150, 811, 51))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: none;\n"
"color: grey;")
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        self.label_16.setGeometry(QtCore.QRect(25, 135, 21, 20))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("icons/ellipsis.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        self.label_17.setGeometry(QtCore.QRect(270, 200, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.widget_2)
        self.label_18.setGeometry(QtCore.QRect(830, 200, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setGeometry(QtCore.QRect(90, 240, 501, 241))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QHeaderView::section { \n"
" background-color: rgba(10, 116, 240, 255);\n"
" color: white;\n"
" border:none; \n"
"}\n"
"\n"
"\n"
"QTableWidget \n"
"{\n"
" color: black;\n"
" border:none; \n"
"}\n"
"\n"
"\n"
"QTableWidget::item::selected\n"
"{\n"
" color: black; \n"
" background-color: rgba(10, 116, 240, 120);\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
" Background: rgba(10, 116, 240, 160);\n"
" Border: 0px solid grey;\n"
" Border-radius: 3px; \n"
" Width: 8px;\n"
"}\n"
"\n"
"\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(159)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 500, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(25)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"border-radius: 14px;\n"
"color: white;\n"
"}")
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 500, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(25)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"border-radius: 14px;\n"
"color: white;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_7.setGeometry(QtCore.QRect(780, 500, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(25)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"border-radius: 14px;\n"
"color: white;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_8.setGeometry(QtCore.QRect(840, 500, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(25)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"border-radius: 14px;\n"
"color: white;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_20 = QtWidgets.QLabel(self.widget_2)
        self.label_20.setGeometry(QtCore.QRect(240, 40, 581, 55))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("icons/Step2.PNG"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(760, 240, 191, 241))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("QHeaderView::section { \n"
" background-color: rgba(10, 116, 240, 255);\n"
" color: white;\n"
" border:none; \n"
"}\n"
"\n"
"\n"
"QTableWidget \n"
"{\n"
" color: black;\n"
" border:none; \n"
"}\n"
"\n"
"\n"
"QTableWidget::item::selected\n"
"{\n"
" color: black; \n"
" background-color: rgba(10, 116, 240, 120);\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
" Background: rgba(10, 116, 240, 160);\n"
" Border: 0px solid grey;\n"
" Border-radius: 3px; \n"
" Width: 8px;\n"
"}\n"
"\n"
"\n"
"")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(170)
        self.stackedWidget.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget()
        self.widget_3.setObjectName("widget_3")
        self.label_21 = QtWidgets.QLabel(self.widget_3)
        self.label_21.setGeometry(QtCore.QRect(240, 40, 581, 55))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("icons/Step3.PNG"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_3)
        self.label_22.setGeometry(QtCore.QRect(320, 100, 511, 51))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: none;\n"
"")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.widget_3)
        self.label_23.setGeometry(QtCore.QRect(250, 140, 611, 51))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: none;\n"
"color: grey;")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widget_3)
        self.label_24.setGeometry(QtCore.QRect(25, 95, 21, 20))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("icons/ellipsis.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.widget_3)
        self.label_25.setGeometry(QtCore.QRect(25, 135, 21, 20))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("icons/check.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(130, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(450, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_27 = QtWidgets.QLabel(self.widget_3)
        self.label_27.setGeometry(QtCore.QRect(500, 240, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_28.setGeometry(QtCore.QRect(780, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_80 = QtWidgets.QLabel(self.widget_3)
        self.label_80.setGeometry(QtCore.QRect(790, 240, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_29.setGeometry(QtCore.QRect(130, 400, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_81 = QtWidgets.QLabel(self.widget_3)
        self.label_81.setGeometry(QtCore.QRect(110, 360, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.widget_3)
        self.label_82.setGeometry(QtCore.QRect(500, 360, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.radioButton = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton.setGeometry(QtCore.QRect(390, 400, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_2.setGeometry(QtCore.QRect(540, 400, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_30.setGeometry(QtCore.QRect(130, 520, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.label_83 = QtWidgets.QLabel(self.widget_3)
        self.label_83.setGeometry(QtCore.QRect(160, 480, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.widget_3)
        self.label_84.setGeometry(QtCore.QRect(470, 480, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.pushButton_17 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_17.setGeometry(QtCore.QRect(450, 520, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"color: white; \n"
"border-radius: 14px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #0559F0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #0559F0;\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_28 = QtWidgets.QLabel(self.widget_3)
        self.label_28.setGeometry(QtCore.QRect(150, 240, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_83.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_27.raise_()
        self.lineEdit_9.raise_()
        self.label_80.raise_()
        self.lineEdit_28.raise_()
        self.label_81.raise_()
        self.lineEdit_29.raise_()
        self.label_82.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.lineEdit_30.raise_()
        self.label_84.raise_()
        self.pushButton_17.raise_()
        self.label_28.raise_()
        self.lineEdit_8.raise_()
        self.stackedWidget.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget()
        self.widget_4.setObjectName("widget_4")
        self.label_85 = QtWidgets.QLabel(self.widget_4)
        self.label_85.setGeometry(QtCore.QRect(25, 95, 21, 20))
        self.label_85.setText("")
        self.label_85.setPixmap(QtGui.QPixmap("icons/ellipsis.png"))
        self.label_85.setScaledContents(True)
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.widget_4)
        self.label_86.setGeometry(QtCore.QRect(25, 135, 21, 20))
        self.label_86.setText("")
        self.label_86.setPixmap(QtGui.QPixmap("icons/check.png"))
        self.label_86.setScaledContents(True)
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.widget_4)
        self.label_87.setGeometry(QtCore.QRect(240, 40, 581, 55))
        self.label_87.setText("")
        self.label_87.setPixmap(QtGui.QPixmap("icons/Step4.PNG"))
        self.label_87.setScaledContents(True)
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.widget_4)
        self.label_88.setGeometry(QtCore.QRect(340, 100, 631, 51))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_88.setFont(font)
        self.label_88.setStyleSheet("background-color: none;\n"
"")
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.widget_4)
        self.label_89.setGeometry(QtCore.QRect(260, 140, 721, 51))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_89.setFont(font)
        self.label_89.setStyleSheet("background-color: none;\n"
"color: grey;")
        self.label_89.setObjectName("label_89")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_31.setGeometry(QtCore.QRect(130, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_31.setFont(font)
        self.lineEdit_31.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_90 = QtWidgets.QLabel(self.widget_4)
        self.label_90.setGeometry(QtCore.QRect(110, 240, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_90.setFont(font)
        self.label_90.setObjectName("label_90")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_32.setGeometry(QtCore.QRect(450, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_32.setFont(font)
        self.lineEdit_32.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.label_91 = QtWidgets.QLabel(self.widget_4)
        self.label_91.setGeometry(QtCore.QRect(480, 240, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_91.setFont(font)
        self.label_91.setObjectName("label_91")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_33.setGeometry(QtCore.QRect(780, 280, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.label_92 = QtWidgets.QLabel(self.widget_4)
        self.label_92.setGeometry(QtCore.QRect(790, 240, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_92.setFont(font)
        self.label_92.setObjectName("label_92")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_34.setGeometry(QtCore.QRect(130, 400, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_34.setFont(font)
        self.lineEdit_34.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.label_93 = QtWidgets.QLabel(self.widget_4)
        self.label_93.setGeometry(QtCore.QRect(170, 360, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_35.setGeometry(QtCore.QRect(450, 400, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.lineEdit_35.setFont(font)
        self.lineEdit_35.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.label_94 = QtWidgets.QLabel(self.widget_4)
        self.label_94.setGeometry(QtCore.QRect(420, 360, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.label_94.setFont(font)
        self.label_94.setObjectName("label_94")
        self.label_94.raise_()
        self.label_93.raise_()
        self.label_92.raise_()
        self.label_90.raise_()
        self.label_85.raise_()
        self.label_86.raise_()
        self.label_87.raise_()
        self.label_88.raise_()
        self.label_89.raise_()
        self.lineEdit_31.raise_()
        self.label_91.raise_()
        self.lineEdit_32.raise_()
        self.lineEdit_33.raise_()
        self.lineEdit_34.raise_()
        self.lineEdit_35.raise_()
        self.stackedWidget.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget()
        self.widget_5.setObjectName("widget_5")
        self.label_95 = QtWidgets.QLabel(self.widget_5)
        self.label_95.setGeometry(QtCore.QRect(25, 95, 21, 20))
        self.label_95.setText("")
        self.label_95.setPixmap(QtGui.QPixmap("icons/check.png"))
        self.label_95.setScaledContents(True)
        self.label_95.setObjectName("label_95")
        self.label_96 = QtWidgets.QLabel(self.widget_5)
        self.label_96.setGeometry(QtCore.QRect(25, 135, 21, 20))
        self.label_96.setText("")
        self.label_96.setPixmap(QtGui.QPixmap("icons/check.png"))
        self.label_96.setScaledContents(True)
        self.label_96.setObjectName("label_96")
        self.label_97 = QtWidgets.QLabel(self.widget_5)
        self.label_97.setGeometry(QtCore.QRect(240, 40, 581, 55))
        self.label_97.setText("")
        self.label_97.setPixmap(QtGui.QPixmap("icons/Finish.PNG"))
        self.label_97.setScaledContents(True)
        self.label_97.setObjectName("label_97")
        self.label_98 = QtWidgets.QLabel(self.widget_5)
        self.label_98.setGeometry(QtCore.QRect(310, 100, 641, 51))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_98.setFont(font)
        self.label_98.setStyleSheet("background-color: none;\n"
"")
        self.label_98.setObjectName("label_98")
        self.label_99 = QtWidgets.QLabel(self.widget_5)
        self.label_99.setGeometry(QtCore.QRect(410, 140, 531, 51))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_99.setFont(font)
        self.label_99.setStyleSheet("background-color: none;\n"
"color: grey;")
        self.label_99.setObjectName("label_99")
        self.pushButton_18 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_18.setGeometry(QtCore.QRect(340, 250, 371, 81))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(15)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"color: white; \n"
"border-radius: 14px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #0559F0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #0559F0;\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_19.setGeometry(QtCore.QRect(340, 370, 371, 81))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(15)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"color: white; \n"
"border-radius: 14px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #0559F0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #0559F0;\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.stackedWidget.addWidget(self.widget_5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 10, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: none;\n"
"\n"
"font-weight: bold;")
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 90, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"color: black; \n"
"border-radius: 14px;\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/free-icon-personal-data-5891034.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(405, 615, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"color: white; \n"
"border-radius: 14px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #0559F0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #0559F0;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(555, 615, 101, 81))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"color: white; \n"
"border-radius: 14px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #0559F0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #0559F0;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(730, 530, 461, 321))
        self.label_4.setStyleSheet("background-color: none;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("icons/logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 130, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"color: black; \n"
"border-radius: 14px;\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/free-icon-pc-4699800.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Основная информация"))
        self.label_2.setText(_translate("MainWindow", "Укажите основные данные о системном блоке"))
        self.label_6.setText(_translate("MainWindow", "Модель"))
        self.label_7.setText(_translate("MainWindow", "Инвентарный номер"))
        self.label_8.setText(_translate("MainWindow", "IP"))
        self.label_9.setText(_translate("MainWindow", "Виртуальный IP"))
        self.label_10.setText(_translate("MainWindow", "Улица"))
        self.label_11.setText(_translate("MainWindow", "Дом"))
        self.label_12.setText(_translate("MainWindow", "Кабинет"))
        self.label_13.setText(_translate("MainWindow", "Технические характеристики"))
        self.label_14.setText(_translate("MainWindow", "Укажите технические средства и ОС системного блока"))
        self.label_17.setText(_translate("MainWindow", "Тех. средства"))
        self.label_18.setText(_translate("MainWindow", "ОС"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Наименование"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Марка"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Серийный номер"))
        self.pushButton_5.setText(_translate("MainWindow", "-"))
        self.pushButton_6.setText(_translate("MainWindow", "+"))
        self.pushButton_7.setText(_translate("MainWindow", "-"))
        self.pushButton_8.setText(_translate("MainWindow", "+"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Наименование"))
        self.label_22.setText(_translate("MainWindow", "Основная информация"))
        self.label_23.setText(_translate("MainWindow", "Укажите личную информацию о сотруднике"))
        self.label_27.setText(_translate("MainWindow", "Имя"))
        self.label_80.setText(_translate("MainWindow", "Отчество"))
        self.label_81.setText(_translate("MainWindow", "Дата рождения"))
        self.label_82.setText(_translate("MainWindow", "Пол"))
        self.radioButton.setText(_translate("MainWindow", "Мужской"))
        self.radioButton_2.setText(_translate("MainWindow", "Женский"))
        self.label_83.setText(_translate("MainWindow", "СНИЛС"))
        self.label_84.setText(_translate("MainWindow", "Паспорт"))
        self.pushButton_17.setText(_translate("MainWindow", "Прикрепить"))
        self.label_28.setText(_translate("MainWindow", "Фамилия"))
        self.label_88.setText(_translate("MainWindow", "Рабочая информация"))
        self.label_89.setText(_translate("MainWindow", "Укажите рабочую информацию сотрудника"))
        self.label_90.setText(_translate("MainWindow", "Подразделение"))
        self.label_91.setText(_translate("MainWindow", "Звание"))
        self.label_92.setText(_translate("MainWindow", "Должность"))
        self.label_93.setText(_translate("MainWindow", "Регион"))
        self.label_94.setText(_translate("MainWindow", "Номер телефона"))
        self.label_98.setText(_translate("MainWindow", "Информация заполнена"))
        self.label_99.setText(_translate("MainWindow", "Выберите опцию"))
        self.pushButton_18.setText(_translate("MainWindow", "Записать в базу"))
        self.pushButton_19.setText(_translate("MainWindow", "Получить документы"))
        self.label_3.setText(_translate("MainWindow", "МВД"))
        self.pushButton_4.setText(_translate("MainWindow", "Сотрудник"))
        self.pushButton.setText(_translate("MainWindow", "<"))
        self.pushButton_2.setText(_translate("MainWindow", ">"))
        self.pushButton_3.setText(_translate("MainWindow", "АРМ"))


