# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 771)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 660, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"color: white; \n"
"border-radius: 14px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #0559F0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #0559F0;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(450, 30, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 230, 901, 371))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QHeaderView::section { \n"
" background-color: rgba(10, 116, 240, 255);\n"
" color: white;\n"
" border:none; \n"
"}\n"
"\n"
"\n"
"QTableWidget \n"
"{\n"
" color: black;\n"
" border:none; \n"
"}\n"
"\n"
"\n"
"QTableWidget::item::selected\n"
"{\n"
" color: black; \n"
" background-color: rgba(10, 116, 240, 120);\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
" Background: rgba(10, 116, 240, 160);\n"
" Border: 0px solid grey;\n"
" Border-radius: 3px; \n"
" Width: 8px;\n"
"}\n"
"\n"
"\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        font.setStrikeOut(False)
        font.setKerning(False)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 120, 970, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(170, 34))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(170, 34))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(170, 34))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(170, 34))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, -1, 5)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(170, 34))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при наведении, если нужно */\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"    border: 1px solid #0A74F0; /* Измените цвет рамки при фокусе, если нужно */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background-color: white;\n"
"    box-shadow: 2px 2px 5px #0A74F0;\n"
"}\n"
"")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_5.addWidget(self.lineEdit_5)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 660, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"color: white; \n"
"border-radius: 14px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #0559F0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #0559F0;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Поиск"))
        self.label_6.setText(_translate("MainWindow", "Поиск"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Отчество"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "СНИЛС"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Инвентарный номер"))
        self.label.setText(_translate("MainWindow", "Фамилия"))
        self.label_2.setText(_translate("MainWindow", "Имя"))
        self.label_3.setText(_translate("MainWindow", "Отчество"))
        self.label_4.setText(_translate("MainWindow", "СНИЛС"))
        self.label_5.setText(_translate("MainWindow", "Инвентарный номер"))
        self.pushButton_2.setText(_translate("MainWindow", "Перейти"))
