# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Nikita\Desktop\MVD2\untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(423, 339)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 70, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"color: white; \n"
"border-radius: 14px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #0559F0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #0559F0;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 190, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: #0A74F0;\n"
"color: white; \n"
"border-radius: 14px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #0559F0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #0559F0;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Создать"))
        self.pushButton_2.setText(_translate("MainWindow", "Найти"))
